name: Deploy to AWS S3 and invalidate CloudFront distribution
run-name: Deploy to AWS S3 with CloudFront #${{ github.run_number }}
on: [workflow_dispatch]

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  deploy-to-s3-with-cloudfront:
    runs-on: ubuntu-latest
    needs: build-and-test
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Deploy to S3 and invalidate CloudFront
        uses: reggionick/s3-deploy@v4
        with:
          folder: .
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
          files-to-include: '{.*/**,**}'
